unpackaged/main/default/objects/Account/fields/Hierarchy_Adjusted__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_Adjusted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hierarchy Adjusted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Hierarchy_Level__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_Level__c</fullName>
    <description>Indicates where the account sits within the hierarchy in Salesforce, with 1 indicating an ultimate parent.</description>
    <label>Hierarchy Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Total_Child_Locations__c.field-meta.xml
<CustomField>
    <fullName>Total_Child_Locations__c</fullName>
    <description>Rollup summary of the number of location accounts underneath the Account in Salesforce</description>
    <label>Total Child Locations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ultimate_Parent__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ultimate Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Ultimate Parent)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchUltimateParentPopulateAccounts.cls
/**********************************************************
Class: BatchUltimateParentPopulateAccounts 
LastModifiedBy: Cloud connex 05/04/2023
Description: Batch class to populate the Hierarchy Level and Total Child Locations on Accounts Hiearchy
TestClass : BatchUltimateParentPopulateAccountsTest
***********************************************************/
public class BatchUltimateParentPopulateAccounts implements Database.Batchable<sObject>, Schedulable, Database.Stateful{
    
    String theQuery;
    public List<Account> theAllAccounts = new List<Account>();
    public BatchUltimateParentPopulateAccounts(String Query) {
        this.theQuery = Query;
    }
    
    public BatchUltimateParentPopulateAccounts() {
        this.theQuery = 'SELECT Id, Name, ParentId, Ultimate_Parent__c, Type, Hierarchy_Level__c, Hierarchy_Adjusted__c, Total_Child_Locations__c FROM Account WHERE Ultimate_Parent__c = null AND Hierarchy_Adjusted__c = true';
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(theQuery);
    }
    
    public void execute(Database.BatchableContext BC, List<Account> theAccList) {
        
        UltimateParentPopulateAccounts populateAccounts = new UltimateParentPopulateAccounts(theAccList);
        populateAccounts.execute();
        
        theAllAccounts.addAll(theAccList);
        
    }
    
    public void finish(Database.BatchableContext BC){
        Map<Id,Account> theAcntUpdatesMap = new Map<Id,Account>();
        for(Account theAcnt: theAllAccounts){
            if(theAcnt.Hierarchy_Adjusted__c == true){
                theAcnt.Hierarchy_Adjusted__c = false;
                theAcntUpdatesMap.put(theAcnt.Id, theAcnt);
            }
        }
        
        update theAcntUpdatesMap.values();
    }
    
    public void execute(SchedulableContext sc) {
        Id batchJobId = Database.executeBatch(new BatchUltimateParentPopulateAccounts(), 200);
    }
    
}